import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const baseVerbWords = [
  {
    english: 'to go',
    german: 'gehen',
    thirdForm: 'ging',
    perfekt: 'ist gegangen',
  },
  {
    english: 'to come',
    german: 'kommen',
    thirdForm: 'kam',
    perfekt: 'ist gekommen',
  },
  {
    english: 'to eat',
    german: 'essen',
    thirdForm: 'aß',
    perfekt: 'hat gegessen',
  },
  {
    english: 'to drink',
    german: 'trinken',
    thirdForm: 'trank',
    perfekt: 'hat getrunken',
  },
  {
    english: 'to sleep',
    german: 'schlafen',
    thirdForm: 'schlief',
    perfekt: 'hat geschlafen',
  },
  {
    english: 'to write',
    german: 'schreiben',
    thirdForm: 'schrieb',
    perfekt: 'hat geschrieben',
  },
  {
    english: 'to read',
    german: 'lesen',
    thirdForm: 'las',
    perfekt: 'hat gelesen',
  },
  {
    english: 'to speak',
    german: 'sprechen',
    thirdForm: 'sprach',
    perfekt: 'hat gesprochen',
  },
  {
    english: 'to see',
    german: 'sehen',
    thirdForm: 'sah',
    perfekt: 'hat gesehen',
  },
  {
    english: 'to find',
    german: 'finden',
    thirdForm: 'fand',
    perfekt: 'hat gefunden',
  },
  {
    english: 'to give',
    german: 'geben',
    thirdForm: 'gab',
    perfekt: 'hat gegeben',
  },
  {
    english: 'to take',
    german: 'nehmen',
    thirdForm: 'nahm',
    perfekt: 'hat genommen',
  },
  {
    english: 'to stand',
    german: 'stehen',
    thirdForm: 'stand',
    perfekt: 'hat gestanden',
  },
  {
    english: 'to sit',
    german: 'sitzen',
    thirdForm: 'saß',
    perfekt: 'hat gesessen',
  },
  {
    english: 'to lie (be located)',
    german: 'liegen',
    thirdForm: 'lag',
    perfekt: 'hat gelegen',
  },
  {
    english: 'to stay',
    german: 'bleiben',
    thirdForm: 'blieb',
    perfekt: 'ist geblieben',
  },
  {
    english: 'to think',
    german: 'denken',
    thirdForm: 'dachte',
    perfekt: 'hat gedacht',
  },
  {
    english: 'to know (a fact)',
    german: 'wissen',
    thirdForm: 'wusste',
    perfekt: 'hat gewusst',
  },
  {
    english: 'to know (someone)',
    german: 'kennen',
    thirdForm: 'kannte',
    perfekt: 'hat gekannt',
  },
  {
    english: 'to work',
    german: 'arbeiten',
    thirdForm: 'arbeitete',
    perfekt: 'hat gearbeitet',
  },
  {
    english: 'to live',
    german: 'leben',
    thirdForm: 'lebte',
    perfekt: 'hat gelebt',
  },
  {
    english: 'to learn',
    german: 'lernen',
    thirdForm: 'lernte',
    perfekt: 'hat gelernt',
  },
  {
    english: 'to study',
    german: 'studieren',
    thirdForm: 'studierte',
    perfekt: 'hat studiert',
  },
  {
    english: 'to understand',
    german: 'verstehen',
    thirdForm: 'verstand',
    perfekt: 'hat verstanden',
  },
  {
    english: 'to begin',
    german: 'beginnen',
    thirdForm: 'begann',
    perfekt: 'hat begonnen',
  },
  {
    english: 'to end',
    german: 'enden',
    thirdForm: 'endete',
    perfekt: 'hat geendet',
  },
  {
    english: 'to make',
    german: 'machen',
    thirdForm: 'machte',
    perfekt: 'hat gemacht',
  },
  {
    english: 'to play',
    german: 'spielen',
    thirdForm: 'spielte',
    perfekt: 'hat gespielt',
  },
  {
    english: 'to help',
    german: 'helfen',
    thirdForm: 'half',
    perfekt: 'hat geholfen',
  },
  {
    english: 'to ask',
    german: 'fragen',
    thirdForm: 'fragte',
    perfekt: 'hat gefragt',
  },
  {
    english: 'to answer',
    german: 'antworten',
    thirdForm: 'antwortete',
    perfekt: 'hat geantwortet',
  },
  {
    english: 'to bring',
    german: 'bringen',
    thirdForm: 'brachte',
    perfekt: 'hat gebracht',
  },
  {
    english: 'to buy',
    german: 'kaufen',
    thirdForm: 'kaufte',
    perfekt: 'hat gekauft',
  },
  {
    english: 'to sell',
    german: 'verkaufen',
    thirdForm: 'verkaufte',
    perfekt: 'hat verkauft',
  },
  {
    english: 'to pay',
    german: 'bezahlen',
    thirdForm: 'bezahlte',
    perfekt: 'hat bezahlt',
  },
  {
    english: 'to need',
    german: 'brauchen',
    thirdForm: 'brauchte',
    perfekt: 'hat gebraucht',
  },
  {
    english: 'to call',
    german: 'rufen',
    thirdForm: 'rief',
    perfekt: 'hat gerufen',
  },
  {
    english: 'to hear',
    german: 'hören',
    thirdForm: 'hörte',
    perfekt: 'hat gehört',
  },
  {
    english: 'to wait',
    german: 'warten',
    thirdForm: 'wartete',
    perfekt: 'hat gewartet',
  },
  {
    english: 'to drive',
    german: 'fahren',
    thirdForm: 'fuhr',
    perfekt: 'ist gefahren',
  },
  {
    english: 'to fly',
    german: 'fliegen',
    thirdForm: 'flog',
    perfekt: 'ist geflogen',
  },
  {
    english: 'to fall',
    german: 'fallen',
    thirdForm: 'fiel',
    perfekt: 'ist gefallen',
  },
  {
    english: 'to run',
    german: 'laufen',
    thirdForm: 'lief',
    perfekt: 'ist gelaufen',
  },
  {
    english: 'to swim',
    german: 'schwimmen',
    thirdForm: 'schwamm',
    perfekt: 'ist geschwommen',
  },
  {
    english: 'to build',
    german: 'bauen',
    thirdForm: 'baute',
    perfekt: 'hat gebaut',
  },
  {
    english: 'to cook',
    german: 'kochen',
    thirdForm: 'kochte',
    perfekt: 'hat gekocht',
  },
  {
    english: 'to open',
    german: 'öffnen',
    thirdForm: 'öffnete',
    perfekt: 'hat geöffnet',
  },
  {
    english: 'to close',
    german: 'schließen',
    thirdForm: 'schloss',
    perfekt: 'hat geschlossen',
  },
  {
    english: 'to start',
    german: 'anfangen',
    thirdForm: 'fing an',
    perfekt: 'hat angefangen',
  },
  {
    english: 'to finish',
    german: 'beenden',
    thirdForm: 'beendete',
    perfekt: 'hat beendet',
  },
  {
    english: 'to bring along',
    german: 'mitbringen',
    thirdForm: 'brachte mit',
    perfekt: 'hat mitgebracht',
  },
  {
    english: 'to come back',
    german: 'zurückkommen',
    thirdForm: 'kam zurück',
    perfekt: 'ist zurückgekommen',
  },
  {
    english: 'to get up',
    german: 'aufstehen',
    thirdForm: 'stand auf',
    perfekt: 'ist aufgestanden',
  },
  {
    english: 'to go out',
    german: 'ausgehen',
    thirdForm: 'ging aus',
    perfekt: 'ist ausgegangen',
  },
  {
    english: 'to put on (clothes)',
    german: 'anziehen',
    thirdForm: 'zog an',
    perfekt: 'hat angezogen',
  },
  {
    english: 'to wash',
    german: 'waschen',
    thirdForm: 'wusch',
    perfekt: 'hat gewaschen',
  },
  {
    english: 'to send',
    german: 'schicken',
    thirdForm: 'schickte',
    perfekt: 'hat geschickt',
  },
  {
    english: 'to show',
    german: 'zeigen',
    thirdForm: 'zeigte',
    perfekt: 'hat gezeigt',
  },
  {
    english: 'to stay overnight',
    german: 'übernachten',
    thirdForm: 'übernachtete',
    perfekt: 'hat übernachtet',
  },
  {
    english: 'to mean',
    german: 'meinen',
    thirdForm: 'meinte',
    perfekt: 'hat gemeint',
  },
  {
    english: 'to believe',
    german: 'glauben',
    thirdForm: 'glaubte',
    perfekt: 'hat geglaubt',
  },
  {
    english: 'to hope',
    german: 'hoffen',
    thirdForm: 'hoffte',
    perfekt: 'hat gehofft',
  },
  {
    english: 'to wait for',
    german: 'warten auf',
    thirdForm: 'wartete',
    perfekt: 'hat gewartet',
  },
  {
    english: 'to begin (start)',
    german: 'anfangen',
    thirdForm: 'fing an',
    perfekt: 'hat angefangen',
  },
  {
    english: 'to happen',
    german: 'passieren',
    thirdForm: 'passierte',
    perfekt: 'ist passiert',
  },
  {
    english: 'to stay',
    german: 'bleiben',
    thirdForm: 'blieb',
    perfekt: 'ist geblieben',
  },
  {
    english: 'to drive off',
    german: 'abfahren',
    thirdForm: 'fuhr ab',
    perfekt: 'ist abgefahren',
  },
  {
    english: 'to arrive',
    german: 'ankommen',
    thirdForm: 'kam an',
    perfekt: 'ist angekommen',
  },
  {
    english: 'to wake up',
    german: 'aufwachen',
    thirdForm: 'wachte auf',
    perfekt: 'ist aufgewacht',
  },
  {
    english: 'to work out (train)',
    german: 'trainieren',
    thirdForm: 'trainierte',
    perfekt: 'hat trainiert',
  },
  {
    english: 'to buy',
    german: 'kaufen',
    thirdForm: 'kaufte',
    perfekt: 'hat gekauft',
  },
  {
    english: 'to sell',
    german: 'verkaufen',
    thirdForm: 'verkaufte',
    perfekt: 'hat verkauft',
  },
  {
    english: 'to laugh',
    german: 'lachen',
    thirdForm: 'lachte',
    perfekt: 'hat gelacht',
  },
  {
    english: 'to cry',
    german: 'weinen',
    thirdForm: 'weinte',
    perfekt: 'hat geweint',
  },
  {
    english: 'to sing',
    german: 'singen',
    thirdForm: 'sang',
    perfekt: 'hat gesungen',
  },
  {
    english: 'to dance',
    german: 'tanzen',
    thirdForm: 'tanzte',
    perfekt: 'hat getanzt',
  },
  {
    english: 'to play',
    german: 'spielen',
    thirdForm: 'spielte',
    perfekt: 'hat gespielt',
  },
  {
    english: 'to clean',
    german: 'putzen',
    thirdForm: 'putzte',
    perfekt: 'hat geputzt',
  },
  {
    english: 'to repair',
    german: 'reparieren',
    thirdForm: 'reparierte',
    perfekt: 'hat repariert',
  },
  {
    english: 'to cook',
    german: 'kochen',
    thirdForm: 'kochte',
    perfekt: 'hat gekocht',
  },
  {
    english: 'to order',
    german: 'bestellen',
    thirdForm: 'bestellte',
    perfekt: 'hat bestellt',
  },
  {
    english: 'to use',
    german: 'benutzen',
    thirdForm: 'benutzte',
    perfekt: 'hat benutzt',
  },
  {
    english: 'to try',
    german: 'versuchen',
    thirdForm: 'versuchte',
    perfekt: 'hat versucht',
  },
  {
    english: 'to explain',
    german: 'erklären',
    thirdForm: 'erklärte',
    perfekt: 'hat erklärt',
  },
  {
    english: 'to describe',
    german: 'beschreiben',
    thirdForm: 'beschrieb',
    perfekt: 'hat beschrieben',
  },
  {
    english: 'to decide',
    german: 'entscheiden',
    thirdForm: 'entschied',
    perfekt: 'hat entschieden',
  },
  {
    english: 'to win',
    german: 'gewinnen',
    thirdForm: 'gewann',
    perfekt: 'hat gewonnen',
  },
  {
    english: 'to lose',
    german: 'verlieren',
    thirdForm: 'verlor',
    perfekt: 'hat verloren',
  },
  {
    english: 'to forget',
    german: 'vergessen',
    thirdForm: 'vergaß',
    perfekt: 'hat vergessen',
  },
  {
    english: 'to remember',
    german: 'sich erinnern',
    thirdForm: 'erinnerte sich',
    perfekt: 'hat sich erinnert',
  },
  {
    english: 'to wash oneself',
    german: 'sich waschen',
    thirdForm: 'wusch sich',
    perfekt: 'hat sich gewaschen',
  },
  {
    english: 'to shave',
    german: 'sich rasieren',
    thirdForm: 'rasierte sich',
    perfekt: 'hat sich rasiert',
  },
  {
    english: 'to get dressed',
    german: 'sich anziehen',
    thirdForm: 'zog sich an',
    perfekt: 'hat sich angezogen',
  },
  {
    english: 'to relax',
    german: 'sich entspannen',
    thirdForm: 'entspannte sich',
    perfekt: 'hat sich entspannt',
  },
  {
    english: 'to hurry',
    german: 'sich beeilen',
    thirdForm: 'beeilte sich',
    perfekt: 'hat sich beeilt',
  },
  {
    english: 'to meet',
    german: 'treffen',
    thirdForm: 'traf',
    perfekt: 'hat getroffen',
  },
  {
    english: 'to call',
    german: 'anrufen',
    thirdForm: 'rief an',
    perfekt: 'hat angerufen',
  },
  {
    english: 'to send',
    german: 'senden',
    thirdForm: 'sandte',
    perfekt: 'hat gesandt',
  },
  {
    english: 'to stay',
    german: 'bleiben',
    thirdForm: 'blieb',
    perfekt: 'ist geblieben',
  },
  {
    english: 'to move',
    german: 'ziehen',
    thirdForm: 'zog',
    perfekt: 'ist gezogen',
  },
  {
    english: 'to show',
    german: 'zeigen',
    thirdForm: 'zeigte',
    perfekt: 'hat gezeigt',
  },
  {
    english: 'to think',
    german: 'denken',
    thirdForm: 'dachte',
    perfekt: 'hat gedacht',
  },
  {
    english: 'to work',
    german: 'arbeiten',
    thirdForm: 'arbeitete',
    perfekt: 'hat gearbeitet',
  },
  {
    english: 'to wait',
    german: 'warten',
    thirdForm: 'wartete',
    perfekt: 'hat gewartet',
  },
  {
    english: 'to need',
    german: 'brauchen',
    thirdForm: 'brauchte',
    perfekt: 'hat gebraucht',
  },
];

const prepositionVerbWords = [
  {
    english: 'to pay attention to',
    german: 'achten auf',
    thirdForm: '-',
    perfekt: 'hat geachtet',
  },
  {
    english: 'to start with',
    german: 'anfangen mit',
    thirdForm: 'fing an',
    perfekt: 'hat angefangen',
  },
  {
    english: 'to depend on',
    german: 'abhängen von',
    thirdForm: 'hing ab',
    perfekt: 'hat abgehangen',
  },
  {
    english: 'to answer',
    german: 'antworten auf',
    thirdForm: '-',
    perfekt: 'hat geantwortet',
  },
  {
    english: 'to be angry about',
    german: 'sich ärgern über',
    thirdForm: '-',
    perfekt: 'hat sich geärgert',
  },
  {
    english: 'to stop doing',
    german: 'aufhören mit',
    thirdForm: '-',
    perfekt: 'hat aufgehört',
  },
  {
    english: 'to look after',
    german: 'aufpassen auf',
    thirdForm: '-',
    perfekt: 'hat aufgepasst',
  },
  {
    english: 'to thank someone',
    german: 'sich bedanken bei',
    thirdForm: '-',
    perfekt: 'hat sich bedankt',
  },
  {
    english: 'to thank for',
    german: 'sich bedanken für',
    thirdForm: '-',
    perfekt: 'has sich bedankt',
  },
  {
    english: 'to begin with',
    german: 'beginnen mit',
    thirdForm: 'begann',
    perfekt: 'hat begonnen',
  },
  {
    english: 'to complain about',
    german: 'sich beklagen über',
    thirdForm: '-',
    perfekt: 'hat sich beklagt',
  },
  {
    english: 'to strive for',
    german: 'sich bemühen um',
    thirdForm: '-',
    perfekt: 'hat sich bemüht',
  },
  {
    english: 'to report about',
    german: 'berichten über',
    thirdForm: '-',
    perfekt: 'hat berichtet',
  },
  {
    english: 'to complain about',
    german: 'sich beschweren über',
    thirdForm: '-',
    perfekt: 'hat sich beschwert',
  },
  {
    english: 'to insist on',
    german: 'bestehen auf',
    thirdForm: 'bestand',
    perfekt: 'hat bestanden',
  },
  {
    english: 'to consist of',
    german: 'bestehen aus',
    thirdForm: 'bestand',
    perfekt: 'hat bestanden',
  },
  {
    english: 'to apply for',
    german: 'sich bewerben um',
    thirdForm: 'bewarb sich',
    perfekt: 'hat sich beworben',
  },
  {
    english: 'to refer to',
    german: 'sich beziehen auf',
    thirdForm: 'bezog sich',
    perfekt: 'hat sich bezogen',
  },
  {
    english: 'to ask for',
    german: 'bitten um',
    thirdForm: 'bat',
    perfekt: 'hat gebeten',
  },
  {
    english: 'to think of',
    german: 'denken an',
    thirdForm: 'dachte',
    perfekt: 'hat gedacht',
  },
  {
    english: 'to apologise to',
    german: 'sich entschuldigen bei',
    thirdForm: '-',
    perfekt: 'hat sich entschuldigt',
  },
  {
    english: 'to apologise for',
    german: 'sich entschuldigen für',
    thirdForm: '-',
    perfekt: 'hat sich entschuldigt',
  },
  {
    english: 'to remember',
    german: 'sich erinnern an',
    thirdForm: '-',
    perfekt: 'hat sich erinnert',
  },
  {
    english: 'to ask about',
    german: 'fragen nach',
    thirdForm: '-',
    perfekt: 'hat gefragt',
  },
  {
    english: 'to look forward to',
    german: 'sich freuen auf',
    thirdForm: '-',
    perfekt: 'hat sich gefreut',
  },
  {
    english: 'to be happy about',
    german: 'sich freuen über',
    thirdForm: '-',
    perfekt: 'hat sich gefreut',
  },
  {
    english: 'to be about',
    german: 'es geht um',
    thirdForm: 'ging',
    perfekt: 'ist gegangen',
  },
  {
    english: 'to belong to',
    german: 'gehören zu',
    thirdForm: '-',
    perfekt: 'hat gehört',
  },
  {
    english: 'to believe in',
    german: 'glauben an',
    thirdForm: '-',
    perfekt: 'hat geglaubt',
  },
  {
    english: 'to congratulate on',
    german: 'gratulieren zu',
    thirdForm: '-',
    perfekt: 'hat gratuliert',
  },
  {
    english: 'to be about',
    german: 'sich handeln um',
    thirdForm: '-',
    perfekt: 'hat sich gehandelt',
  },
  {
    english: 'to hope for',
    german: 'hoffen auf',
    thirdForm: '-',
    perfekt: 'hat gehofft',
  },
  {
    english: 'to be interested in',
    german: 'sich interessieren für',
    thirdForm: '-',
    perfekt: 'hat sich interessiert',
  },
  {
    english: 'to fight for',
    german: 'kämpfen für',
    thirdForm: '-',
    perfekt: 'hat gekämpft',
  },
  {
    english: 'to fight against',
    german: 'kämpfen gegen',
    thirdForm: '-',
    perfekt: 'hat gekämpft',
  },
  {
    english: 'to laugh about',
    german: 'lachen über',
    thirdForm: '-',
    perfekt: 'hat gelacht',
  },
  {
    english: 'to suffer from (illness)',
    german: 'leiden an',
    thirdForm: 'litt',
    perfekt: 'hat gelitten',
  },
  {
    english: 'to suffer from (situation)',
    german: 'leiden unter',
    thirdForm: 'litt',
    perfekt: 'hat gelitten',
  },
  {
    english: 'to think about',
    german: 'nachdenken über',
    thirdForm: 'dachte nach',
    perfekt: 'hat nachgedacht',
  },
  {
    english: 'to suit',
    german: 'passen zu',
    thirdForm: '-',
    perfekt: 'hat gepasst',
  },
  {
    english: 'to react to',
    german: 'reagieren auf',
    thirdForm: '-',
    perfekt: 'hat reagiert',
  },
  {
    english: 'to write to',
    german: 'schreiben an',
    thirdForm: 'schrieb',
    perfekt: 'hat geschrieben',
  },
  {
    english: 'to write about',
    german: 'schreiben über',
    thirdForm: 'schrieb',
    perfekt: 'hat geschrieben',
  },
  {
    english: 'to worry about',
    german: 'sich sorgen um',
    thirdForm: '-',
    perfekt: 'hat sich gesorgt',
  },
  {
    english: 'to speak with',
    german: 'sprechen mit',
    thirdForm: 'sprach',
    perfekt: 'hat gesprochen',
  },
  {
    english: 'to speak about',
    german: 'sprechen über',
    thirdForm: 'sprach',
    perfekt: 'hat gesprochen',
  },
  {
    english: 'to die of',
    german: 'sterben an',
    thirdForm: 'starb',
    perfekt: 'ist gestorben',
  },
  {
    english: 'to take part in',
    german: 'teilnehmen an',
    thirdForm: 'nahm teil',
    perfekt: 'hat teilgenommen',
  },
  {
    english: 'to dream of',
    german: 'träumen von',
    thirdForm: '-',
    perfekt: 'hat geträumt',
  },
  {
    english: 'to meet with',
    german: 'sich treffen mit',
    thirdForm: 'traf sich',
    perfekt: 'hat sich getroffen',
  },
  {
    english: 'to talk with',
    german: 'sich unterhalten mit',
    thirdForm: 'unterhielt sich',
    perfekt: 'hat sich unterhalten',
  },
  {
    english: 'to talk about',
    german: 'sich unterhalten über',
    thirdForm: 'unterhielt sich',
    perfekt: 'hat sich unterhalten',
  },
  {
    english: 'to say goodbye to',
    german: 'sich verabschieden von',
    thirdForm: '-',
    perfekt: 'hat sich verabschiedet',
  },
  {
    english: 'to rely on',
    german: 'sich verlassen auf',
    thirdForm: 'verließ sich',
    perfekt: 'hat sich verlassen',
  },
  {
    english: 'to fall in love with',
    german: 'sich verlieben in',
    thirdForm: '-',
    perfekt: 'hat sich verliebt',
  },
  {
    english: 'to do without',
    german: 'verzichten auf',
    thirdForm: '-',
    perfekt: 'hat verzichtet',
  },
  {
    english: 'to prepare for',
    german: 'sich vorbereiten auf',
    thirdForm: '-',
    perfekt: 'hat sich vorbereitet',
  },
  {
    english: 'to warn about',
    german: 'warnen vor',
    thirdForm: '-',
    perfekt: 'hat gewarnt',
  },
  {
    english: 'to wait for',
    german: 'warten auf',
    thirdForm: '-',
    perfekt: 'hat gewartet',
  },
  {
    english: 'to wonder about',
    german: 'sich wundern über',
    thirdForm: '-',
    perfekt: 'hat sich gewundert',
  },
  {
    english: 'to doubt',
    german: 'zweifeln an',
    thirdForm: '-',
    perfekt: 'hat gezweifelt',
  },
  {
    english: 'to look after',
    german: 'sich kümmern um',
    thirdForm: '-',
    perfekt: 'hat sich gekümmert',
  },
  {
    english: 'to get used to',
    german: 'sich gewöhnen an',
    thirdForm: '-',
    perfekt: 'hat sich gewöhnt',
  },
  {
    english: 'to inform oneself about',
    german: 'sich informieren über',
    thirdForm: '-',
    perfekt: 'hat sich informiert',
  },
  {
    english: 'to inquire about',
    german: 'sich erkundigen nach',
    thirdForm: '-',
    perfekt: 'has sich erkundigt',
  },
];
async function main() {
  const user = await prisma.user.upsert({
    where: { email: 'demo@eazy-lingo.dev' },
    update: {},
    create: {
      email: 'demo@eazy-lingo.dev',
      name: 'Demo User',
    },
  });

  await prisma.word.deleteMany();
  await prisma.set.deleteMany();

  await prisma.set.create({
    data: {
      name: 'German Verbs',
      isCommon: true,
      words: {
        create: baseVerbWords,
      },
    },
  });

  await prisma.set.create({
    data: {
      name: 'Verben mit Praepositionen',
      isCommon: true,
      words: {
        create: prepositionVerbWords,
      },
    },
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
