name: Deploy to EC2

on:
  workflow_run:
    workflows: ['Publish Docker Images']
    types:
      - completed

jobs:
  deploy:
    environment: EC2_HOST
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo 
            cd /opt/eazy-lingo

            echo 
            docker compose -f docker-compose.ec2.yml pull --no-cache

            echo 
            docker compose -f docker-compose.ec2.yml down
            docker compose -f docker-compose.ec2.yml up -d

            echo
            docker system prune -f

            echo "✅ Деплой успешно завершён!"
